name: Create pull request in remote repository
on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      commit:
        required: true
        type: string
      assignee:
        required: true
        type: string
      setup-action:
        type: string
    secrets:
      AUTOMATION_APP_ID:
        required: true
      AUTOMATION_APP_PRIVATE_KEY:
        required: true

jobs:
  workflow_call:
    name: Create or update PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: current-meta-repository
          ref: ${{ github.ref_name }}

      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/${{ inputs.repository }}
          path: service-repository
          ref: ${{ github.ref_name }}
          fetch-depth: 0
          submodules: true

      - name: Checkout meta repository commit
        working-directory: service-repository/.git/modules/openslides-meta/
        run: git fetch origin && git checkout ${{ inputs.commit }}

      - name: Update repository files
        if: inputs.setup-action != ''
        uses: jenseng/dynamic-uses@v1
        with:
          uses: ./current-meta-repository/.github/actions/${{ inputs.setup-action }}

      - name: Generate access token
        uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.AUTOMATION_APP_ID }}
          private_key: ${{ secrets.AUTOMATION_APP_PRIVATE_KEY }}

      - name: Create or update PR
        uses: peter-evans/create-pull-request@v7
        with:
          path: service-repository
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: Update meta repository
          branch: dep/update-meta-repo
          delete-branch: true
          title: "Update meta repository (${{ github.ref_name }})"
          body: "Triggered by commit [${{ inputs.commit }}](https://github.com/${{ github.repository_owner }}/openslides-meta/commit/${{ inputs.commit }})"
          reviewers: ${{ inputs.assignee }}
          assignees: ${{ inputs.assignee }}
          labels: dependencies
          milestone: 4
